# Generated by Django 4.1.13 on 2024-07-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, default='Admin', max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('cnic', models.CharField(blank=True, max_length=256, null=True)),
                ('department_name', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAttend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('face_feature', models.TextField(blank=True, null=True)),
                ('blob_face_feature', models.BinaryField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=256, null=True)),
                ('camera_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('T1', models.IntegerField(default=0)),
                ('T2', models.IntegerField(default=0)),
                ('T3', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('is_moved', models.BooleanField(default=False)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.personregistration')),
            ],
        ),
        migrations.CreateModel(
            name='FaceCoding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('face_feature', models.TextField(blank=True, null=True)),
                ('blob_face_feature', models.BinaryField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=256, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.personregistration')),
            ],
        ),
    ]
