# Generated by Django 4.1 on 2024-07-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminlogin',
            table='admin_login',
        ),
    ]
