# Generated by Django 4.1 on 2024-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_adminlogin_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personregistration',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
