# Generated by Django 4.1 on 2024-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_personregistration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facecoding',
            name='time_sent',
            field=models.DateTimeField(),
        ),
    ]
