# Generated by Django 4.1 on 2024-08-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_facecoding_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facecoding',
            old_name='person_id',
            new_name='person',
        ),
    ]
