# Generated by Django 4.1 on 2024-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_person_id_facecoding_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
