# Generated by Django 4.1 on 2024-08-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_adminlogin_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
