# Generated by Django 4.1 on 2024-08-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_adminlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personattend',
            old_name='person_id',
            new_name='person',
        ),
    ]
