# Generated by Django 4.1 on 2024-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_person_id_personattend_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='compress_images'),
        ),
    ]
