# Generated by Django 4.1 on 2024-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_facecoding_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='camera_img'),
        ),
    ]
