# Generated by Django 4.1 on 2024-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_facecoding_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personattend',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
