# Generated by Django 4.1 on 2024-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_facecoding_img_url_alter_personattend_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facecoding',
            name='time_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
