# Generated by Django 4.1 on 2024-08-31 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_facecoding_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='face_feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128),
        ),
        migrations.AlterField(
            model_name='facecoding',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.personregistration'),
        ),
        migrations.AlterField(
            model_name='personattend',
            name='face_feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128),
        ),
        migrations.AlterField(
            model_name='personattend',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.personregistration'),
        ),
    ]
