# Generated by Django 4.1 on 2024-09-01 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_facecoding_face_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='face_feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2048),
        ),
        migrations.AlterField(
            model_name='personattend',
            name='camera_id',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
