# Generated by Django 4.1 on 2024-09-02 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_facecoding_face_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecoding',
            name='face_feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128),
        ),
        migrations.AlterField(
            model_name='personattend',
            name='face_feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128),
        ),
    ]
